version: '3'
services:
  nestjs-social-development:
    image: mysql:8.0.25
    container_name: nestjs-social-development
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: social_database

      LANG: C.UTF-8
    ports:
      - 23306:3306

  nestjs-social-test:
    image: mysql:8.0.25
    container_name: nestjs-social-test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: social_database
      LANG: C.UTF-8
    ports:
      - 23305:3306
